# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dotnet
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 5.0.101
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

      # Install dependencies          
      - name: Install dependencies
        run: dotnet restore KostalApiClient.csproj      

      - name: Publish
        run: | # | character makes the "run" property multi-line, so we can put multiple commands in the same step
          mkdir __out
          dotnet pack -c Release -o __out --no-restore  -p:PackageVersion=1.0.1
          dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}}
          rm -rf __out
          

